-- Auto-generated seed data for Barrington MTG Collection
DELETE FROM analysis;
DELETE FROM cards;
DELETE FROM decks;

INSERT INTO decks (id,title,theme,commander,alt_commander,pips,position) VALUES ('ool','Blight Curse','jund','Auntie Ool, Cursewretch',NULL,'k,r,g',0);
INSERT INTO decks (id,title,theme,commander,alt_commander,pips,position) VALUES ('zimone','Jump Scare!','simic','Zimone, Mystery Unraveler',NULL,'g,u',1);
INSERT INTO decks (id,title,theme,commander,alt_commander,pips,position) VALUES ('ashling','Ashling Elemental','five','Ashling, the Limitless',NULL,'w,u,k,r,g',2);
INSERT INTO decks (id,title,theme,commander,alt_commander,pips,position) VALUES ('kilo','Counter Intelligence','kilo','Kilo, Apogee Mind',NULL,'u,r,w',3);
INSERT INTO decks (id,title,theme,commander,alt_commander,pips,position) VALUES ('jeskai','Jeskai Striker','jeskai','Shiko and Narset, Unified','Elsha, Threefold Master','u,r,w',4);
INSERT INTO decks (id,title,theme,commander,alt_commander,pips,position) VALUES ('mardu','Mardu Surge','mardu','Zurgo Stormrender','Neriv, Crackling Vanguard','r,w,k',5);
INSERT INTO decks (id,title,theme,commander,alt_commander,pips,position) VALUES ('tmnt','TMNT Commander','tmnt','Heroes in a Half Shell',NULL,'w,u,k,r,g',6);

INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Splendid Agony','AKH',1,0,0);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Ferrafor, Young Yew','ECC',1,0,1);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Archfiend of Ifnir','ECC',1,0,2);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Cankerbloom','ONE',1,0,3);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Puppeteer Clique','ECC',1,0,4);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Binding the Old Gods','ECC',1,0,5);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Grave Titan','ECC',1,0,6);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Liliana, Death Wielder','ECC',1,0,7);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Decimator Beetle','AKH',1,0,8);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Grim Poppet','ECC',1,0,9);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Swamp','IKO',7,0,10);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Flourishing Defenses','ECC',1,0,11);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Persist','ECC',1,0,12);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Nesting Grounds','ECC',1,0,13);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Pull from the Grave','SOS',1,0,14);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Blowfly Infestation','ECC',1,0,15);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Everlasting Torment','ECC',1,0,16);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Grave Venerations','ECC',1,0,17);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Unnatural Restoration','ONE',1,0,18);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Auntie Ool, Cursewretch (Borderless)','ECC',1,0,19);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Nest of Scarabs','AKH',1,0,20);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Arcane Signet','ECC',1,0,21);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Chimil, the Inner Sun','PRE',1,0,22);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Commander''s Sphere','ECC',1,0,23);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Contagion Clasp','DDF',1,0,24);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Savage Lands','ECC',1,0,25);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Wickersmith''s Tools','ECC',1,0,26);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Sheltered Thicket','ECC',1,0,27);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Dragonskull Summit','ECC',1,0,28);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Evolving Wilds','ECL',1,0,29);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Riveteers Overlook','ECC',1,0,30);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Ifnir Deadlands','ECC',1,0,31);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Path of Ancestry','ECC',1,0,32);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Smoldering Marsh','ECC',1,0,33);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Terramorphic Expanse','ECC',1,0,34);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Cinder Glade','ECC',1,0,35);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Canyon Slough','ECC',1,0,36);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Command Tower','ECC',1,0,37);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Woodland Cemetery','ECC',1,0,38);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Vernal Fen','ECC',1,0,39);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Rakdos Carnarium (Retro Frame)','BRC',1,0,40);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Golgari Rot Farm','ECC',1,0,41);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Wickerbough Elder','ECC',1,0,42);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Village Pillagers','ECC',1,0,43);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Tree of Perdition','ECC',1,0,44);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','The Scorpion God','ECC',1,0,45);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','The Reaper, King No More (Borderless)','ECC',1,0,46);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Soul Snuffers','ECC',1,0,47);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Shriekmaw','ECC',1,0,48);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Massacre Girl, Known Killer','ECC',1,0,49);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Kulrath Knight','ECC',1,0,50);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Midnight Banshee','ECC',1,0,51);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Necroskitter','ECC',1,0,52);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Ignoble Hierarch','ECC',1,0,53);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Hapatra, Vizier of Poisons','ECC',1,0,54);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Glissa Sunslayer','PRE',1,0,55);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Evolution Sage','ECC',1,0,56);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Devoted Druid','ECC',1,0,57);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Dread Tiller','ECC',1,0,58);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Carnifex Demon','ECC',1,0,59);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Cavalier of Thorns','ECC',1,0,60);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Channeler Initiate','ECC',1,0,61);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Dusk Urchins','ECC',1,0,62);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Vraska, Betrayal''s Sting','ECC',1,0,63);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Assassin''s Trophy','ECC',1,0,64);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Cast Down','CMR',1,0,65);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Fire Covenant','ECC',1,0,66);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Grim Affliction','LIST',1,0,67);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Infernal Grasp','ECC',1,0,68);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Terminate','ECC',1,0,69);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Kodama''s Reach','ECC',1,0,70);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Black Sun''s Zenith','ECC',1,0,71);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Painful Truths','ECC',1,0,72);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Incremental Blight','ECC',1,0,73);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Harmonize','ECC',1,0,74);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Night''s Whisper (Retro Frame)','OHP',1,0,75);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Skinrender','ECC',1,0,76);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Sinister Gnarlbark','ECC',1,0,77);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Gruul Turf','BLC',1,0,78);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Exotic Orchard','EOC',1,0,79);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Rootbound Crag','BLC',1,0,80);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Sol Ring','PIP',1,0,81);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Sudden Spoiling','C14',1,0,82);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Putrefy','ECC',1,0,83);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Forest','UND',6,0,84);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('ool','deck','Mountain','IKO',4,0,85);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Rampant Growth','M10',1,0,0);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Explore','JMP',1,0,1);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Gaea''s Revenge','PRE',1,0,2);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Beanstalk Giant','DSC',1,0,3);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Zimone''s Experiment','SOS',1,0,4);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Island','GRN',8,0,5);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Forest','GRN',8,0,6);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Escape Tunnel','TMT',1,0,7);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Explosive Vegetation','DMC',1,0,8);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Zimone, Mystery Unraveler (Borderless)','DSC',1,0,9);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Kodama''s Reach','DMC',1,0,10);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','They Came from the Pipes','DSC',1,0,11);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Shigeki, Jukai Visionary','NEO',1,0,12);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Simic Signet','DSC',1,0,13);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Quandrix Campus','DSC',1,0,14);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Overwhelming Stampede','DSC',1,0,15);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Yavimaya Coast','DSC',1,0,16);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Flooded Grove','M3C',1,0,17);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Aesi, Tyrant of Gyre Strait','DSC',1,0,18);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Vesuvan Shapeshifter','C19',1,0,19);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Brine Elemental','TSP',1,0,20);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Deathmist Raptor','C19',1,0,21);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Hydra Omnivore','DSC',1,0,22);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Oversimplify','DSC',1,0,23);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Rampant Growth','DSC',1,0,24);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Simic Growth Chamber','DSC',1,0,25);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Evolving Wilds','CMD',1,0,26);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Citanul Hierophants','DSC',1,0,27);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Retreat to Coralhelm','DSC',1,0,28);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Myriad Landscape','A25',1,0,29);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Greater Tanuki','DSC',1,0,30);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Hinterland Harbor','DSC',1,0,31);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Myriad Landscape (C14)','LIST',1,0,32);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Tangled Islet','DSC',1,0,33);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Rashmi, Eternities Crafter','DSC',1,0,34);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Augur of Autumn','EOC',1,0,35);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Overflowing Basin','OTC',1,0,36);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Sol Ring','DSC',1,0,37);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Scroll of Fate','DSC',1,0,38);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Wilderness Reclamation (Retro Frame)','RVR',1,0,39);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Overgrown Zealot','DSK',1,0,40);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Growth Spiral','DSC',1,0,41);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Ashaya, Soul of the Wild','DSC',1,0,42);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Arixmethes, Slumbering Isle','DSC',1,0,43);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Castle Vantress','DSC',1,0,44);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Temple of Mystery','DSC',1,0,45);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Worldspine Wurm','LIST',1,0,46);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Multani, Yavimaya''s Avatar','PRE',1,0,47);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Counterspell','DSC',1,0,48);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Cackling Counterpart','DSC',1,0,49);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Vineglimmer Snarl','DSC',1,0,50);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Eureka Moment','DSC',1,0,51);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Primordial Mist','DSC',1,0,52);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Temur War Shaman','DSC',1,0,53);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Thunderfoot Baloth','DSC',1,0,54);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Whisperwood Elemental','DSC',1,0,55);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Terramorphic Expanse','DSK',1,0,56);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Cultivate','DSC',1,0,57);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Zimone''s Hypothesis','DSC',1,0,58);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Dig Through Time','DSC',1,0,59);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Aether Gale','SOC',1,0,60);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Beast Within','DSC',1,0,61);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Temple of the False God','WOC',1,0,62);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Biomass Mutation','DSC',1,0,63);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Glitch Interpreter','DSC',1,0,64);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Sakura-Tribe Elder','DSC',1,0,65);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Yedora, Grave Gardener','DSC',1,0,66);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Sandwurm Convergence','DSC',1,0,67);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Secret Plans','KTK',1,0,68);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Trygon Predator','DSC',1,0,69);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Ezuri''s Predation','DSC',1,0,70);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Scute Swarm','DSC',1,0,71);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Yavimaya Elder','DSC',1,0,72);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Ash Barrens','DSC',1,0,73);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Mosswort Bridge','BLC',1,0,74);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Arcane Signet','DSC',1,0,75);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Curator Beastie','DSC',1,0,76);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Command Tower','LCC',1,0,77);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Reality Shift','SOC',1,0,78);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Brokers Hideout','SNC',1,0,79);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Shriekwood Devourer','DSC',1,0,80);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Reliquary Tower','SOC',1,0,81);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Tatyova, Benthic Druid','DOM',1,0,82);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Kefnet the Mindful','AKH',1,0,83);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Body of Knowledge','DSC',1,0,84);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('zimone','deck','Trail of Mystery','DSC',1,0,85);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Double Jump // Flying Kick','TMC',1,0,0);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Skateboard','TMT',1,0,1);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Ninja Pizza','TMC',1,0,2);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Escape Tunnel','TMT',1,0,3);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Super Combo','TMC',1,0,4);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Irma, Part-Time Mutant','TMC',1,0,5);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Command Tower','TMC',1,0,6);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Dimension X Pizzasaur','TMC',1,0,7);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Harmonize','TMC',1,0,8);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Forest','TMT',4,0,9);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Island','TMT',2,0,10);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Mountain','TMT',1,0,11);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Swamp','TMT',2,0,12);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Plains','TMT',2,0,13);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Undergrowth Stadium','TMC',1,0,14);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Thriving Isle','TMC',1,0,15);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Thriving Grove','TMC',1,0,16);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Sodden Verdure','TMC',1,0,17);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Vernal Fen','TMC',1,0,18);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Path of Ancestry','TMC',1,0,19);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Foot Headquarters','TMT',1,0,20);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Rootbound Crag','TMC',1,0,21);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Hinterland Harbor','TMC',1,0,22);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Thriving Moor','TMC',1,0,23);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Evolving Wilds','TMC',1,0,24);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Fabled Passage','TMC',1,0,25);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Ash Barrens','TMC',1,0,26);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Arcane Signet','TMC',1,0,27);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Arcade Cabinet','TMC',1,0,28);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Aggro Amalgam - Voracious Hydra','TMC',1,0,29);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Assassin''s Trophy','TMC',1,0,30);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Coin of Mastery','TMC',1,0,31);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Casey Jones, Back Alley Brute','TMC',1,0,32);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Chromatic Lantern','TMC',1,0,33);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Anchovy & Banana Pizza','TMT',1,0,34);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','April O''Neil, Live on the Scene','TMC',1,0,35);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Dragonskull Summit','TMC',1,0,36);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Cultivate','TMC',1,0,37);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Lessons from Life','TMT',1,0,38);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Mikey & Leo, Chaos & Order','TMT',1,0,39);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Continue?','TMC',1,0,40);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','City of Brass','TMC',1,0,41);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Vanquish the Horde','TMC',1,0,42);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Fast Forward','TMC',1,0,43);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Together Forever','TMC',1,0,44);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Krang, the All-Powerful','TMC',1,0,45);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Sol Ring','TMC',1,0,46);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Shredder, Shadow Master','TMC',1,0,47);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Exploding Barrel','TMC',1,0,48);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Slash Clone - Steelbane Hydra','TMC',1,0,49);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Mole Module','TMC',1,0,50);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Tokka & Rahzar, Unsupervised','TMC',1,0,51);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Roadkill Rodney','TMC',2,0,52);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Rocksteady, Mutant Marauder','TMC',1,0,53);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Zog, Triceraton Castaway','TMT',1,0,54);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Leonardo, the Balance (Borderless)','TMC',1,0,55);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Raphael, the Muscle (Borderless)','TMC',1,0,56);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Donatello, the Brains (Borderless)','TMC',1,0,57);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Michelangelo, the Heart (Borderless)','TMC',1,0,58);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Splinter, the Mentor (Borderless)','TMC',1,0,59);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Heroes in a Half Shell (Borderless)','TMC',1,0,60);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Wave Goodbye','TMC',1,0,61);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Humongous Fungus - Corpsejack Menace','TMC',1,0,62);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Level Up','TMC',1,0,63);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Baxter, Fly in the Ointment','TMC',1,0,64);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Swift Demise','TMC',1,0,65);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Marauding Mutagen - Acidic Slime','TMC',1,0,66);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Special Move','TMC',1,0,67);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','High Score','TMC',1,0,68);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Mona Lisa, Science Geek','TMT',1,0,69);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Ray Fillet, Wave Warrior','TMC',1,0,70);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Endless Foot Assault','TMC',1,0,71);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Grand Coliseum','TMC',1,0,72);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Hidden Hideout','TMC',1,0,73);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Leatherhead, Iron Gator','TMC',1,0,74);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Cinder Glade','TMC',1,0,75);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','TCRI Building','TMT',1,0,76);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Smoldering Marsh','TMC',1,0,77);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Rain-Slicked Copse','TMC',1,0,78);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Spire Garden','TMC',1,0,79);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Exotic Orchard','TMC',1,0,80);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Sunken Hollow','TMC',1,0,81);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Turtle Lair','TMT',1,0,82);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Blasphemous Act','TMC',1,0,83);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Big Apple, 3 a.m.','TMC',1,0,84);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Big Mother Mouser','TMC',1,0,85);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Here Comes a New Hero!','TMC',1,0,86);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Raphael, Tough Turtle','TMT',1,0,87);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Negate','TMT',1,0,88);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Foot Chopper','TMC',1,0,89);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Shellshock','TMC',1,0,90);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Biogenic Ooze','TMC',1,0,91);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES ('tmnt','deck','Bebop, Skull & Crossbones','TMC',1,0,92);

INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Cinderhaze Wretch','SHM',1,0,0);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Dirgur Focusmage','SOC',1,0,1);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Prismari Pianist','SOC',1,0,2);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Inspired Skypainter','SOC',1,0,3);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Aligned Heart','TDC',1,0,4);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Curse of Opulence','TDC',1,0,5);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Shiny Impetus','TDC',1,0,6);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Ancestral Vision','TDC',2,0,7);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Faithless Looting','TDC',2,0,8);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Skaab Ruinator','DSC',2,0,9);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Kheru Spellsnatcher','DSC',2,0,10);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Hua Tuo, Honored Physician','C13',2,0,11);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Growing Dread','DSK',2,0,12);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Vastlands Scavenger','SOS',1,0,13);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Nyxathid','JMP',1,0,14);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Burning Curiosity','ECL',2,0,15);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Eventide''s Shadow','ECC',2,0,16);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Aberrant Return','ECC',2,0,17);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Soul Immolation','ECL',2,0,18);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Puca''s Covenant','ECC',2,0,19);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Pest Mascot','SOS',1,0,20);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Acrobatic Leap','LCI',1,0,21);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Prismatic Undercurrents','ECL',1,0,22);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Wistfulness','PPECL',1,0,23);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Lofty Dreams','ECL',1,0,24);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Impolite Entrance','ECL',1,0,25);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Unbury','ECL',1,0,26);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Chomping Changeling','ECL',1,0,27);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Prideful Feastling','ECL',1,0,28);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Flame-Chain Mauler','ECL',1,0,29);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Great Forest Druid','ECL',2,0,30);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Goldmeadow Nomad','ECL',2,0,31);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Silvergill Peddler','ECL',2,0,32);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Bile-Vial Boggart','ECL',2,0,33);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Feed the Flames','ECL',2,0,34);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Gishath, Sun''s Avatar','MEDIA',1,0,35);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Riling Dawnbreaker (Showcase)','TDM',1,0,36);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Frostcliff Siege (Borderless)','TDM',1,0,37);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Narset''s Rebuke','TDM',1,0,38);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Kin-Tree Nurturer','TDM',1,0,39);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Salt Road Packbeast','TDM',1,0,40);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Boulderborn Dragon (Showcase)','TDM',1,0,41);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Narset, Jeskai Waymaster','TDM',1,0,42);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Traveling Botanist','TDM',1,0,43);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Riverwheel Sweep','TDM',1,0,44);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Marshal of the Lost','TDM',1,0,45);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Unburied Earthcarver','TDM',1,0,46);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Dismal Backwater','TDM',1,0,47);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Rescue Leopard','TDM',1,0,48);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Marauding Blight-Priest','FDN',1,0,49);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Ambush Wolf','FDN',1,0,50);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Think Twice','ISD',1,0,51);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Cathar Commando','FDN',1,0,52);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Burst Lightning','FDN',1,0,53);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Macabre Waltz','FDN',1,0,54);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Spitfire Lagac','FDN',1,0,55);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Exsanguinate','FDN',1,0,56);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Sylvan Scavenging','FDN',1,0,57);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Tatyova, Benthic Druid','FDN',1,0,58);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Reclamation Sage','FDN',1,0,59);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Incinerating Blast','FDN',1,0,60);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Iceridge Serpent','TDM',1,0,61);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Adorned Crocodile','TDM',1,0,62);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Sultai Devotee','TDM',1,0,63);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Captivating Cave','LCI',1,0,64);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Oltec Cloud Guard','LCI',1,0,65);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Deconstruction Hammer','LCI',1,0,66);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Ancestral Reminiscence','LCI',1,0,67);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Kinjalli''s Dawnrunner','LCI',1,0,68);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Ancestors'' Aid','LCI',1,0,69);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Family Reunion','LCI',1,0,70);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Akal Pakal, First Among Equals','PPLCI',1,0,71);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Glimpse the Core','LCI',1,0,72);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Thrashing Brontodon (Borderless)','LCI',1,0,73);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Nicanzil, Current Conductor','LCI',1,0,74);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Undergrowth Stadium','TMC',1,0,75);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Game Over','TMC',1,0,76);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Royal Treatment','SOA',1,0,77);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Mouser Attack!','TMT',3,0,78);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Pumpkin Bombardment','SPM',1,0,79);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Growth Curve','SOS',1,0,80);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Go Ninja Go','TMT',1,0,81);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Grapple with Death','SOS',1,0,82);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Brilliance Unleashed','TMT',1,0,83);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Simic Guildgate','GTC',1,0,84);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Vibrant Cityscape','TMC',1,0,85);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Spectacle Summit','SOS',1,0,86);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Skycoach Waypoint','SOS',1,0,87);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Simic Guildgate','CLU',1,0,88);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Thornwood Falls','DSC',1,0,89);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Festering Thicket','ECC',1,0,90);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Opal Palace','ECC',1,0,91);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Ominous Asylum','SPM',1,0,92);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Paradox Gardens','SOS',3,0,93);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Drownyard Temple','DSC',1,0,94);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Graduation Day','SOS',2,0,95);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Abundant Growth','AVR',1,0,96);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Wild Growth (Retro Frame)','DMR',1,0,97);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Nylea''s Presence','THS',1,0,98);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Additive Evolution','SOS',1,0,99);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Threats Around Every Corner','DSK',1,0,100);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Flamespeaker''s Will','JOU',1,0,101);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Font of Ire','JOU',1,0,102);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Gremlin Infestation','AER',1,0,103);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Charred Foyer // Warped Space (Borderless)','DSK',1,0,104);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Lightning Diadem','JOU',1,0,105);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Buried in the Garden','MKM',1,0,106);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Hamato Guardian Stance','TMT',2,0,107);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Erode','SOS',1,0,108);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Deft Dismissal','AER',1,0,109);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Grounded for Life','TMT',1,0,110);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Ajani''s Response','SOS',1,0,111);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Fractal Anomaly','SOS',1,0,112);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Chase Inspiration','SOS',2,0,113);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Banishing Betrayal','SOS',1,0,114);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Crippling Chill','KTK',1,0,115);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Cancel','KTK',1,0,116);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Divergent Equation','SOS',1,0,117);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Mind Transfer Protocol','TMT',2,0,118);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Muse''s Encouragement','SOS',2,0,119);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Homesickness','SOS',1,0,120);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Giant Growth','SOA',1,0,121);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Royal Treatment','SOA',1,0,122);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Lumaret''s Favor','SOS',1,0,123);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Burrog Barrage','SOS',1,0,124);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Rouse the Mob','JOU',1,0,125);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Cathartic Pyre','MID',1,0,126);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Hungry Flames','AER',1,0,127);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Starfall','JOU',1,0,128);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Heated Argument','SOS',1,0,129);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Fungal Infection','DOM',1,0,130);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Coat with Venom','DTK',1,0,131);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Masterful Flourish','SOS',1,0,132);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Death in the Family','TMT',1,0,133);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Stomped by the Foot','TMT',1,0,134);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Butcher''s Glee','DTK',1,0,135);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Wander Off','SOS',1,0,136);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Flatten','DTK',1,0,137);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Proctor''s Gaze','SOS',1,0,138);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Embrace the Paradox','SOS',2,0,139);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Taigam''s Scheming','KTK',1,0,140);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Donatello''s Technique','TMT',1,0,141);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Self-Reflection','LCI',1,0,142);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Cowabunga!','TMT',3,0,143);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Wild Hypothesis','SOS',1,0,144);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Follow the Lumarets','SOS',1,0,145);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Mutant Chain Reaction','TMT',1,0,146);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Wildcall','FRF',1,0,147);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Disorienting Choice','DSC',1,0,148);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Tome Blast','SOS',2,0,149);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Flurry of Horns','JOU',1,0,150);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Dread Fugue','VOW',1,0,151);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Defeat','DTK',1,0,152);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Mind Rot','DTK',1,0,153);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Stargaze','SOA',1,0,154);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Splinter''s Technique','TMT',1,0,155);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Thirst for Identity','ECL',1,0,156);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Electro''s Bolt','SPM',1,0,157);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Oft-Nabbed Goat','ECC',1,0,158);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Roar of Endless Song (Borderless)','TDM',1,0,159);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Stalactite Dagger','ECL',1,0,160);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Pitiless Fists','ECL',1,0,161);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Wanderbrine Trapper','ECL',1,0,162);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Hallowed Fountain','PPECL',1,1,163);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Squawkroaster','ECL',2,0,164);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Trail of Mystery','PRE',1,0,165);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Midnight Tilling','ECL',1,0,166);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Cruel Truths','TDM',1,0,167);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Sagu Wildling','TDM',1,0,168);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Highspire Bell-Ringer','TDM',1,0,169);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Tempest Hawk','TDM',1,0,170);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Underfoot Underdogs','TDM',1,0,171);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Lightfoot Technique','TDM',1,0,172);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Monastery Messenger','TDM',1,0,173);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Overwhelming Surge','TDM',1,0,174);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Jeskai Brushmaster','TDM',1,0,175);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Bite Down','FDN',1,0,176);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Fake Your Own Death','FDN',1,0,177);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Sure Strike','FDN',1,0,178);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Healer''s Hawk','FDN',1,0,179);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Refute','FDN',1,0,180);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Revenge of the Rats','FDN',1,0,181);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Appeal to Eirdu','ECL',1,0,182);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Involuntary Employment','FDN',1,0,183);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Prideful Parent','FDN',1,0,184);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Duty Beyond Death','TDM',1,0,185);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Whirlwing Stormbrood (Showcase)','TDM',1,0,186);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Dreadwing Scavenger','FDN',1,0,187);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Brazen Scourge','KLD',1,0,188);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Herd Heirloom','TDM',1,0,189);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Rite of Renewal','TDM',1,0,190);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Elvish Archdruid','FDN',1,0,191);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Wind-Scarred Crag','TDM',1,0,192);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Cat Collector','FDN',1,0,193);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Wild Growth','DMR',1,0,194);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Hoarder''s Greed','ECC',1,0,195);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Cathartic Reunion','ECC',1,0,196);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Lasting Tarfire','ECL',1,0,197);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Forgotten Ancient','AC2',1,0,198);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Spider-Gwen, Free Spirit','SPM',1,0,199);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Foreboding Statue','VOW',1,0,200);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Zealous Lorecaster','SOS',1,0,201);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Raphael, Most Attitude (Borderless)','TMT',1,0,202);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Melancholic Poet','SOS',1,0,203);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Blind Creeper','5DN',1,0,204);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Foot Mystic','TMT',1,0,205);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Tunnel Rats','TMT',1,0,206);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Squirrelanoids','TMT',1,0,207);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Savanti Romero, Time''s Exile','TMT',1,0,208);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Infested Thrinax','M3C',1,0,209);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Oroku Saki, Shredder Rising','TMT',1,0,210);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Rat King, Pale Piper','TMC',1,0,211);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Gallant Citizen','SPM',1,0,212);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Foot Ninjas','TMT',1,0,213);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Inkling Mascot','SOS',1,0,214);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Ancient Lumberknot','LIST',1,0,215);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Rhino, Barreling Brute','SPM',1,0,216);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Shriek, Treblemaker','SPM',1,0,217);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Startled Relic Sloth','SOS',1,0,218);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Queza, Augur of Agonies','SNC',1,0,219);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Fractal Mascot','SOS',2,0,220);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Pterafractyl','SOS',1,0,221);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Slithering Cryptid','TMT',1,0,222);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Genghis Frog','TMT',1,0,223);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Nobody','TMT',1,0,224);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Paradox Surveyor','SOS',1,0,225);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Kianne, Corrupted Memory (Borderless)','DSC',1,0,226);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Prowler, Clawed Thief','SPM',1,0,227);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Krang & Shredder','TMT',1,0,228);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Mob Lookout','SPM',1,0,229);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Skullsnap Nuisance','DSK',1,0,230);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Vulture, Scheming Scavenger','SPM',1,0,231);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Rona, Sheoldred''s Faithful (Showcase)','DMU',1,0,232);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Ichorplate Golem','ONE',1,0,233);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Reito Sentinel','NEO',1,0,234);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Hulking Metamorph','BRO',1,0,235);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Watchers of the Dead','AKH',1,0,236);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Sundering Archaic','SOS',1,0,237);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Biblioplex Tomekeeper','SOS',1,0,238);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Rancorous Archaic','SOS',1,0,239);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Barricade Breaker','AER',1,0,240);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Transcendent Archaic','SOS',1,0,241);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Page, Loose Leaf','SOS',1,0,242);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Burnished Hart','CLB',1,0,243);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Heavyweight Demolisher','BRO',1,0,244);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Spotter Thopter','BRO',1,0,245);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Fallaji Dragon Engine','BRO',1,0,246);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Atraxa''s Skitterfang','ONE',1,0,247);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Chrome Dome','TMT',1,0,248);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Lodestone Needle','LCI',1,0,249);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Seer''s Sundial','M3C',2,0,250);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Strixhaven Skycoach','SOS',1,0,251);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Ugin, Eye of the Storms','TDM',1,1,252);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Arc Spitter','SNC',1,0,253);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Dagger of the Worthy','HOU',1,0,254);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Everything Pizza','TMT',1,0,255);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Anchovy & Banana Pizza','TMT',1,0,256);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Abiding Grace','MH2',1,0,257);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Uneasy Alliance','TMT',1,0,258);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Aerial Modification','AER',1,0,259);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Singing Bell Strike','KTK',1,0,260);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Zoetic Glyph','LCI',1,0,261);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Goblin Glasswright','SOS',1,0,262);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Stegron the Dinosaur Man','SPM',1,0,263);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Raging Goblinoids','SPM',1,0,264);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Satyr Hoplite','JOU',2,0,265);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Sigiled Skink','JOU',2,0,266);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Masked Meower','SPM',2,0,267);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Reinforced Ronin','NEO',2,0,268);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Strife Scholar','SOS',2,0,269);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Bladetusk Boar','JOU',2,0,270);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Pensive Minotaur','JOU',2,0,271);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Alluring Suitor','VOW',2,0,272);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Tempestra, Dame of Games','TMC',1,0,273);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Electric Seaweed','TMC',1,0,274);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Purple Dragon Punks','TMT',1,0,275);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Old Hob, Alleycat Blues','TMT',1,0,276);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Qarsi Sadist','DTK',1,0,277);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Adventurous Eater','SOS',1,0,278);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Poisoner''s Apprentice','SOS',1,0,279);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Lecturing Scornmage','SOS',1,0,280);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Hand of Silumgar','DTK',1,0,281);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Marsh Hulk','LIST',1,0,282);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Kolaghan Skirmisher','DTK',1,0,283);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Taxi Driver','SPM',2,0,284);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Vulturous Aven','DTK',1,0,285);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Silumgar Butcher','DTK',1,0,286);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Reckless Imp','DTK',1,0,287);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Wandering Tombshell','DTK',1,0,288);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Tymaret, Chosen from Death','MUL',1,0,289);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Nested Ghoul','J22',1,0,290);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Forum Necroscribe','SOS',1,0,291);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Shambling Goblin','DTK',1,0,292);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Sibsig Icebreakers','DTK',1,0,293);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Noxious Newt','SOS',1,0,294);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Covert Technician (Showcase)','NEO',1,0,295);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Nightshade Dryad','MH3',1,0,296);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Zoo Escapees','TMT',1,0,297);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Shopkeeper''s Bane','SOS',1,0,298);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Emil, Vastlands Roamer','SOS',1,0,299);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Hungry Graffalon','SOS',2,0,300);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Aberrant Manawurm','SOS',1,0,301);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Tenured Concocter','SOS',2,0,302);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Rocksteady, Crash Courser','TMT',1,0,303);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Greater Sandwurm','LIST',1,0,304);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Spider-Islanders','SPM',1,0,305);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Molten Man, Inferno Incarnate','SPM',1,0,306);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Angry Rabble','SPM',1,0,307);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Superior Foes of Spider-Man','SPM',1,0,308);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Dimensional Exile','TMT',1,0,309);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Shattered Acolyte','SOS',1,0,310);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Lita, Little Orphan Amphibian','TMT',1,0,311);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Action News Crew','TMT',1,0,312);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Rehearsed Debater','SOS',1,0,313);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Deadeye Harpooner','AER',1,0,314);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','High-Flying Ace','TMT',1,0,315);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Leonardo, Big Brother','TMT',1,0,316);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Honorbound Page','SOS',1,0,317);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Summoned Dromedary','SOS',1,0,318);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Fugitive Droid','TMT',1,0,319);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Knowledge Seeker','TLA',1,0,320);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Wetland Sambar','KTK',1,0,321);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Master Pakku','TLA',1,0,322);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Landscape Painter','SOS',1,0,323);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Buzz Bots','TMT',1,0,324);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Matterbending Mage','SOS',1,0,325);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Textbook Tabulator','SOS',2,0,326);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Jeskai Windscout','KTK',1,0,327);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Scaldkin','KTK',1,0,328);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Teo, Spirited Glider','TLA',1,0,329);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Donatello, Turtle Techie','TMT',1,0,330);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Ray Fillet, Man Ray','TMT',1,0,331);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Mystic of the Hidden Way','KTK',1,0,332);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Orysa, Tide Choreographer','SOS',1,0,333);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Whirlwind Adept','KTK',1,0,334);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Glacial Stalker','KTK',1,0,335);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Monastery Flock','KTK',1,0,336);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Council of Echoes','LCI',1,0,337);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Kraven''s Cats','SPM',1,0,338);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Environmental Scientist','SOS',1,0,339);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Mindful Biomancer','SOS',1,0,340);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Mushroom Watchdogs','LTR',1,0,341);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Meteor Golem','MOC',1,0,342);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Chain Reaction','AFC',1,0,343);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Hollowmurk Siege (Borderless)','TDM',2,0,344);
INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (NULL,'loose','Giggling Skitterspike','DSC',1,1,345);
