// Generates seed.sql from data/decks.json + data/loose.json
// Run with:  npm run build-seed
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const decks = JSON.parse(readFileSync(join(root, "data", "decks.json"), "utf8"));
const loose = JSON.parse(readFileSync(join(root, "data", "loose.json"), "utf8"));

const q = (v) =>
  v === null || v === undefined ? "NULL" : `'${String(v).replace(/'/g, "''")}'`;

const lines = [];
lines.push("-- Auto-generated by scripts/build-seed.mjs — do not edit by hand.");
lines.push("DELETE FROM analysis;");
lines.push("DELETE FROM cards;");
lines.push("DELETE FROM decks;");
lines.push("");

// Decks
decks.forEach((d, i) => {
  lines.push(
    `INSERT INTO decks (id,title,theme,commander,alt_commander,pips,position) VALUES (` +
      `${q(d.id)},${q(d.title)},${q(d.theme)},${q(d.commander)},${q(d.alt)},${q(d.pips.join(","))},${i});`
  );
});
lines.push("");

// Deck cards
decks.forEach((d) => {
  d.cards.forEach((c, i) => {
    lines.push(
      `INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (` +
        `${q(d.id)},'deck',${q(c.n)},${q(c.s)},${c.q || 1},0,${i});`
    );
  });
});
lines.push("");

// Loose cards (some flagged for_sale)
loose.forEach((c, i) => {
  lines.push(
    `INSERT INTO cards (deck_id,location,name,set_code,qty,for_sale,position) VALUES (` +
      `NULL,'loose',${q(c.n)},${q(c.s)},${c.q || 1},${c.fs ? 1 : 0},${i});`
  );
});
lines.push("");

const deckCards = decks.reduce((s, d) => s + d.cards.length, 0);
writeFileSync(join(root, "seed.sql"), lines.join("\n"));
console.log(
  `Wrote seed.sql — ${decks.length} decks, ${deckCards} deck cards, ${loose.length} loose cards.`
);
